### ISSUE TITLE
New trait for creating stub file without `pyo3/experimental-inspect` feature

### ISSUE THREAD

**Issue by termoshtt** [Jij-Inc/pyo3-stub-gen#16]
`experimental-inspect` has very limited feature. For example, `Option<String>` should generate `str | None` (or `Optional[str]`) in stub file, but it generates `Any`.

**Comment by aldanor** [comment]
`Option<>` of anything seems to be mapping to `PyAny` 🙁 And it's quite typical to have in the signature for kwargs that default to `None`.
