### ISSUE TITLE
 Pyclass support for Rust enums

### ISSUE THREAD

**Issue by cardigan1008** [Jij-Inc/pyo3-stub-gen#67]
I attempted to apply #[gen_stub_pyclass] to an enum with #[pyclass], but encountered a macro error indicating that a struct was expected. Is this issue due to pyo3-stub-gen not yet supporting enums, or did I possibly misuse the macro?

The enum in question is structured as follows:
```rust
#[cfg_attr(feature = "python", gen_stub_pyclass)]
#[derive(Copy, Clone, Debug, PartialEq, PartialOrd, Eq, Ord)]
#[cfg_attr(feature = "python", pyclass(eq, eq_int))]
pub enum Example {
    // enums
}
```

**Comment by termoshtt** [comment]
There is `#[gen_stub_pyclass_enum]`
https://docs.rs/pyo3-stub-gen-derive/latest/pyo3_stub_gen_derive/attr.gen_stub_pyclass_enum.html
https://github.com/Jij-Inc/pyo3-stub-gen/blob/main/examples/pure/src/lib.rs#L91C1-L100C2

**Comment by cardigan1008** [comment]
Thanks!
